name: SonarCloud Analysis

on:
  push:
    branches:
      - feature/Sonarcloud

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Build with MSBuild
        run: dotnet build --configuration Release

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           with:
          args: >
            -Dsonar.organization=SanderWieringa
            -Dsonar.projectKey=sanderwieringa
